services:
  # Servicio principal de la aplicación
  - type: web
    name: discord-ai-comparison
    env: node
    plan: free
    buildCommand: npm install --production
    startCommand: npm start
    healthCheckPath: /
    # Variables de entorno básicas
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: discord-ai-comparison
          property: port
    # Variables sensibles desde Environment Group
    envVarsFromGroup: ai-bot-secrets
    # Configuración de región
    regions:
      - oregon
    # Configuración de escalado
    scaling:
      minInstances: 0  # Permite que se apague cuando no se usa (plan gratuito)
      maxInstances: 1
    # Auto-deploy desde GitHub
    autoDeploy: true
    # Configuración adicional para evitar conflictos
    preDeployCommand: "pkill -f 'node server.js' || true"
